# Generated by Django 3.1.2 on 2020-11-03 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gymapp', '0002_auto_20201103_0648'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='description',
            field=models.TextField(default=False),
        ),
    ]
