# Generated by Django 3.1.2 on 2020-11-06 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gymapp', '0003_category_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pricing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration', models.CharField(max_length=25)),
                ('price', models.CharField(max_length=25)),
            ],
        ),
    ]
