# Generated by Django 3.1.2 on 2020-11-06 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gymapp', '0004_pricing'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricing',
            name='item',
            field=models.CharField(default=False, max_length=25),
        ),
    ]
