# Generated by Django 3.1.2 on 2020-11-07 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gymapp', '0008_about_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='SelfInformation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='GymHut', max_length=10)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=30)),
                ('location', models.CharField(max_length=10)),
                ('maps', models.URLField()),
            ],
        ),
    ]
