# Generated by Django 3.1.2 on 2020-11-07 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gymapp', '0009_selfinformation'),
    ]

    operations = [
        migrations.AddField(
            model_name='selfinformation',
            name='time',
            field=models.CharField(default=False, max_length=50),
        ),
    ]
