# Generated by Django 3.1.2 on 2020-11-07 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gymapp', '0010_selfinformation_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='selfinformation',
            name='locationDesc',
            field=models.TextField(null=True),
        ),
    ]
