# Generated by Django 3.1.2 on 2020-11-07 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gymapp', '0011_selfinformation_locationdesc'),
    ]

    operations = [
        migrations.AddField(
            model_name='selfinformation',
            name='locationTitle',
            field=models.CharField(max_length=80, null=True),
        ),
    ]
