# Generated by Django 3.1.2 on 2020-11-07 02:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gymapp', '0012_selfinformation_locationtitle'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='selfinformation',
            name='location',
        ),
    ]
