# Generated by Django 3.1.2 on 2020-11-08 07:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gymapp', '0015_user'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='Customer',
        ),
    ]
