# Generated by Django 3.1.2 on 2020-11-12 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gymapp', '0016_auto_20201108_1319'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('images', models.ImageField(blank=True, null=True, upload_to='')),
            ],
        ),
    ]
