# Generated by Django 3.1.2 on 2020-11-24 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gymapp', '0024_blog_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricing',
            name='offer',
            field=models.CharField(max_length=25, null=True),
        ),
    ]
