# Generated by Django 3.1.2 on 2020-11-24 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gymapp', '0025_pricing_offer'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricing',
            name='offerprice',
            field=models.CharField(max_length=25, null=True),
        ),
    ]
