# Generated by Django 3.1.2 on 2020-11-25 07:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gymapp', '0027_member'),
    ]

    operations = [
        migrations.RenameField(
            model_name='member',
            old_name='price',
            new_name='duration',
        ),
    ]
