# Generated by Django 3.1.2 on 2020-11-26 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gymapp', '0028_auto_20201125_1322'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='status',
        ),
    ]
