# Generated by Django 3.1.2 on 2020-11-26 14:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gymapp', '0031_member_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gymapp.customer'),
        ),
    ]
