# Generated by Django 3.1.2 on 2020-11-26 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gymapp', '0032_auto_20201126_2021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='customer',
            field=models.CharField(max_length=100),
        ),
    ]
