# Generated by Django 3.1.2 on 2020-11-27 02:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gymapp', '0033_auto_20201126_2023'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=20)),
                ('types', models.CharField(max_length=100)),
                ('duration', models.CharField(max_length=20)),
                ('date', models.DateTimeField(default=datetime.datetime.today)),
            ],
        ),
    ]
